include:
  - services/ilia.fi/docker-compose.yml  # personal website
  - services/networking/docker-compose.yml  # caddy reverse proxy, wireguard 
  - services/bluesky_bot/docker-compose.yml  # Bluesky yle-selkouutiset bot
  - services/kalevala/docker-compose.yml  # Kalevala game - junction '25
  - services/teapot/docker-compose.yml  # Reticulum node

networks:
  web:
    external: true
