include:
  - ilia.fi/docker-compose.yml  # personal website
  - caddy/docker-compose.yml  # reverse proxy
  - bluesky_bot/docker-compose.yml  # Bluesky yle-selkouutiset bot

networks:
  web:
    external: true
